name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build environment -t myos-environment
    - name: run the Docker image
      run: docker run --rm -it -v $(pwd):/root/env myos-environment
    - name: Build using make
      run: make build-x86_64
